name: PR Script
on:
  pull_request:
    branches:
      - main

jobs:
  link:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x] 
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run test code
        run: npm test
      # 테스트 코드 실패 시 동작
      - name: if fail
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
              const ref = "${{github.ref}}"
              const pull_number = Number(ref.split("/")[2])

              await github.pulls.createReview({
                ...context.repo,
                pull_number,
                body: "테스트 코드를 다시 확인해주세요."
                event: "REQUEST_CHANGES"
              })

              await github.pulls.update({
                ...context.repo,
                pull_number,
                state: 'closed'
              })
          if: failure()
